# This is a basic workflow to help you get started with Actions

name: Frontend deployment

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ frontend ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]
        
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: npm install and build
      run: |
          npm install
          npm run build
    - uses: actions/upload-artifact@master
      with:
          name: artifacts
          path: build

  deploy:
    name: deploy app to AWS
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: download built artifact
        uses: actions/download-artifact@master
        with:
          name: artifacts
          path: build
      
      - name: display structure of artifacts
        run: ls -R
        working-directory: build

      - name: copy file via ssh key
        uses: appleboy/scp-action@master
        with:
          host: "ec2-3-132-233-250.us-east-2.compute.amazonaws.com"
          username: ubuntu
          key: ${{ secrets.AWS }}
          source: "build"
          target: "/home/ubuntu/frontend"
